networks:
  proxynet:
    name: tig_network

services:
  victoriametrics:
    image: victoriametrics/victoria-metrics
    ports:
      - 9090:8428
    command:
      - "--httpListenAddr=:8428"
    networks:
      - proxynet
    restart: always

  grafana:
    image: grafana/grafana
    networks:
      - proxynet
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana:/etc/grafana/provisioning/
    restart: always

