networks:
  tignet:

services:
  init_grafana:
    image: grafana/grafana:latest
    user: root
    entrypoint:
      - /bin/sh
      - -c
      - |
        chown -R 65534:65534 /var/lib/grafana
    volumes:
      - ./storage/grafana:/var/lib/grafana

  victoriametrics:
    container_name: victoriametrics
    image: victoriametrics/victoria-metrics
    ports:
      - 9090:8428
    command:
      - "--httpListenAddr=:8428"
    networks:
      - tignet
    volumes:
      - ./storage/vm:/victoria-metrics-data
    restart: always

  grafana:
    image: grafana/grafana
    hostname: grafana
    networks:
      - tignet
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_INSTALL_PLUGINS=https://github.com/grafana/grafana-infinity-datasource/releases/download/v2.9.5/yesoreyeram-infinity-datasource-2.9.5.zip;yesoreyeram-infinity-datasource
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=victoriametrics-datasource
    volumes:
      - ./storage/grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    user: "65534"
    depends_on:
      - init_grafana
    restart: always
