networks:
  tignet:

services:
  victoriametrics:
    container_name: victoriametrics
    image: victoriametrics/victoria-metrics
    ports:
      - 9090:8428
    command:
      - "--httpListenAddr=:8428"
    networks:
      - tignet
    restart: always

  grafana:
    image: grafana/grafana
    hostname: grafana
    networks:
      - tignet
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_INSTALL_PLUGINS=https://github.com/grafana/grafana-infinity-datasource/releases/download/v2.9.5/yesoreyeram-infinity-datasource-2.9.5.zip;yesoreyeram-infinity-datasource
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=victoriametrics-datasource
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    restart: always
