apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    url: http://victoriametrics:8428
    access: proxy
    isDefault: true
  - name: Infinity
    type: yesoreyeram-infinity-datasource